"use strict";
/* Headless contract check for the dashboard handover document helpers
 * (Feature 6). handover.js is DOM-free, so this harness can exercise the real
 * module: export URL/filename construction, HTML escaping, state summarization
 * and printable-document rendering. It reports structural facts that the
 * Python side asserts. All inputs are synthetic fixture data.
 */

const path = require("path");

const dir = process.argv[2];
const H = require(path.join(dir, "handover.js"));

const FIXTURE = {
  cases: [
    {
      id: "aaaa-bbbb-cccc-dddd",
      severity: "high",
      status: "transporting",
      chief_complaint: 'Chest <pain> & "dyspnea"',
      created_at: "2026-08-11T10:00:00Z",
      eta_minutes: 7,
      acceptance: "accepted",
      prepared_at: "2026-08-11T10:05:00Z",
      recommended_hospital: null,
      patient: { name: "Anita <Sharma> & Co", age: 42, sex: "f" },
      ambulance: { vehicle_number: "AMB-1234" },
      destination_hospital: { name: "City General", city: "Pune" },
    },
  ],
  selectedId: "aaaa-bbbb-cccc-dddd",
  history: [
    {
      timestamp: "2026-08-11T10:00:00Z",
      heart_rate: 118,
      spo2: 91,
      systolic_bp: 90,
      diastolic_bp: 60,
      respiratory_rate: 26,
      temperature: 37.2,
    },
    {
      timestamp: "2026-08-11T10:01:00Z",
      heart_rate: 122,
      spo2: 89,
      systolic_bp: 95,
      diastolic_bp: 62,
      respiratory_rate: 28,
      temperature: 37.4,
    },
  ],
  events: [
    { event_type: "scene_arrival", created_at: "2026-08-11T10:00:00Z" },
    { event_type: "hospital_accept", created_at: "2026-08-11T10:05:00Z" },
  ],
  ecgs: [
    {
      id: "ecg-1",
      captured_at: "2026-08-11T10:02:00Z",
      lead_count: 1,
      paper_speed: "25",
      waveform: {
        channels: [{ name: "I", points: [[0, 10], [2, 12]] }],
        grid: {},
      },
      quality: { checks_passed: true, warnings: [] },
      notes: null,
    },
  ],
};

const out = {};
out.exportUrl = {
  fhir: H.exportUrl("abc-123", "fhir"),
  cda: H.exportUrl("abc-123", "cda"),
};
out.filename = {
  fhir: H.filename("ABCD", "fhir", new Date(2026, 7, 11, 9, 30, 15)),
  cda: H.filename("ABCD", "cda", new Date(2026, 7, 11, 9, 30, 15)),
};
out.escape = {
  amp: H.escape("a & b"),
  lt: H.escape("<script>"),
  gt: H.escape(">"),
  quote: H.escape('"'),
  clean: H.escape("plain"),
};

const s = H.summary(FIXTURE);
out.summary = {
  caseCode: s.caseCode,
  patientName: s.patient.name,
  severity: s.severity,
  status: s.status,
  eta: s.eta,
  acceptance: s.acceptance,
  prepared: s.prepared,
  destination: s.destination,
  ambulance: s.ambulance,
  timelineLabels: s.timeline.map((t) => t.label),
  vitalsCount: s.vitals.count,
  seriesLen: s.vitals.series.heart_rate.length,
  latestHr: s.vitals.latest.heart_rate,
  ecgCount: s.ecgs.length,
  ecgPointCount: s.ecgs[0].pointCount,
  ecgChecksPassed: s.ecgs[0].checksPassed,
};

const html = H.printHtml(s);
out.printHtml = {
  hasBoundary: html.indexOf("not a certified medical record") !== -1,
  hasPatient: html.indexOf("Anita") !== -1,
  hasPatientEscaped: html.indexOf("Anita &lt;Sharma&gt; &amp; Co") !== -1,
  hasComplaintEscaped: html.indexOf("Chest &lt;pain&gt;") !== -1,
  hasNoRawScript: html.indexOf("<script>") === -1,
  hasEcgCanvas: html.indexOf('data-print-trace="ecg-1"') !== -1,
  hasEta: html.indexOf("ETA: 7 min") !== -1,
  hasTimeline: html.indexOf("Scene arrival") !== -1,
  hasGenerated: html.indexOf("Generated by MEDHA LINK Hospital Command") !== -1,
};

const minimal = H.summary({
  cases: [{ id: "zzzz", patient: { name: "B" } }],
  selectedId: "zzzz",
  history: [],
  events: [],
  ecgs: [],
});
const mhtml = H.printHtml(minimal);
out.minimal = {
  caseCode: minimal.caseCode,
  hasNoEcg: mhtml.indexOf("No digitized ECG tracings recorded.") !== -1,
  hasEmptyVitals: mhtml.indexOf("No vital readings recorded.") !== -1,
};

process.stdout.write(JSON.stringify(out));
