"""add ambulance assigned_to

Revision ID: 87d0fce1c8cf
Revises: 91cd1267d0fe
Create Date: 2026-08-11 07:56:22.193425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d0fce1c8cf'
down_revision: Union[str, Sequence[str], None] = '91cd1267d0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ambulances', sa.Column('assigned_to_id', sa.Uuid(), nullable=True))
    op.create_index('ix_ambulances_assigned_to', 'ambulances', ['assigned_to_id'], unique=False)
    op.create_foreign_key(op.f('fk_ambulances_assigned_to_id_users'), 'ambulances', 'users', ['assigned_to_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_ambulances_assigned_to_id_users'), 'ambulances', type_='foreignkey')
    op.drop_index('ix_ambulances_assigned_to', table_name='ambulances')
    op.drop_column('ambulances', 'assigned_to_id')
    # ### end Alembic commands ###
